language: c
script: make
compiler:
  - gcc
  - clang
env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release
  - CFLAGS=-std=c11
os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libbsd-dev
install:
  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
      mkdir install_cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C install_cmake
      export PATH=${PWD}/install_cmake/bin:${PATH}
    else
      brew update
      brew install cmake
    fi
